version: '3.6'

services:
  ollama-ai:
    image: ollama/ollama
    environment:
      OLLAMA_ORIGINS: "*"
      OLLAMA_HOST: "0.0.0.0:11434"
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
    name: ollama