version: '3.6'

services:
  local-ai:
    image: local-ai:local
    build:
      context: ./LocalAI
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/build/models
    command: [ "/usr/bin/local-ai" ]
    networks:
      local-ai:
        aliases:
          - localai

  chroma:
    image: chroma:local
    build:
      context: ./chroma
      dockerfile: Dockerfile
    volumes:
      - ./chroma:/chroma
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config chromadb/log_config.yml
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      local-ai:
        aliases:
          - chroma

  flowise:
    image: flowiseai/flowise
    environment:
      - PORT=${PORT}
      - PASSPHRASE=${PASSPHRASE}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - DEBUG=${DEBUG}
      - DATABASE_PATH=${DATABASE_PATH}
      - APIKEY_PATH=${APIKEY_PATH}
      - SECRETKEY_PATH=${SECRETKEY_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
    ports:
      - '3000:3000'
    volumes:
      - ~/.flowise:/root/.flowise
    command: /bin/sh -c "sleep 3; flowise start"
    networks:
      local-ai:
        aliases:
          - flowise

networks:
  local-ai:
    name: local-ai

volumes:
  chroma-persistent-folder:
    name: chroma-persistent-folder
